services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.7
    container_name: al-folio-site
    ports:
      - "8080:8080"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    command: >
      bash -c "bundle install && bundle exec jekyll serve --watch --port=8080 --host=0.0.0.0 --livereload"
    environment:
      - JEKYLL_ENV=development
